#!/usr/bin/env python3

import rospy
from migrave_person_state_estimation_wrapper.person_state_estimation_wrapper import PersonStateEstimationWrapper

if __name__ == '__main__':
    rospy.init_node("person_state_estimator")
    rospy.Rate(30)
    rospy.loginfo("Person state estimator node is running...")
    person_state_estimator = PersonStateEstimationWrapper()

    try:
        while not rospy.is_shutdown():
            person_state_estimator.run()
            rospy.sleep(0.05)
    except rospy.ROSInterruptException as exc:
        print("person state estimator exiting...")
